# Generated by Django 4.2.29 on 2026-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
