# Generated by Django 4.2.29 on 2026-03-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_manufacturing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_despatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delay_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qa_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_despatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned to Hub'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Despatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Despatched to Customer'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned to Hub'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Despatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Despatched to Customer'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
