# Generated by Django 4.2.29 on 2026-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_completed_manufacturing_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Dispatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Dispatched to Customer'), ('COMPLETED', 'Closed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Dispatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Dispatched to Customer'), ('COMPLETED', 'Closed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
