# Generated by Django 4.2.29 on 2026-03-16 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0004_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned to Hub'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Despatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Despatched to Customer'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ASSIGNED', 'Assigned to Hub'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_TEST', 'Quality Test'), ('COMPLETED_MANUFACTURING', 'Completed Manufacturing'), ('DESPATCHED_TO_WAREHOUSE', 'Despatched to Warehouse'), ('DESPATCHED_TO_CUSTOMER', 'Despatched to Customer'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
