# Generated by Django 4.2.29 on 2026-03-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_supported_skus'),
        ('orders', '0005_alter_order_product_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assigned_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='hubs.hub'),
        ),
    ]
