# Generated by Django 4.2.29 on 2026-03-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiapproval'),
        ('orders', '0006_orderitem_assigned_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ai_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ai_engine.aidecision'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assignment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
