# Generated by Django 4.2.29 on 2026-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_completed_manufacturing_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('DELAY_PREDICTION', 'Delay Prediction'), ('INVENTORY_ALERT', 'Inventory Alert')], max_length=50)),
                ('recommendation', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_EXECUTED', 'Auto Executed'), ('WAITING_APPROVAL', 'Waiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_decisions', to='orders.order')),
            ],
            options={
                'verbose_name': 'AI Decision',
                'verbose_name_plural': 'AI Decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
