# Generated by Django 4.2.29 on 2026-03-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_ai_decision_orderitem_assignment_status'),
        ('ai_engine', '0002_aiapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidecision',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_decisions', to='orders.orderitem'),
        ),
    ]
