# Generated by Django 4.2.29 on 2026-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aidecision_related_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidecision',
            name='execution_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aidecision',
            name='orchestrator_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
