# Generated by Django 4.2.29 on 2026-03-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0004_aidecision_execution_trace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_execute_threshold', models.FloatField(default=85.0, help_text='Confidence % (0–100) at or above which the AI auto-executes without human review.')),
                ('hitl_threshold', models.FloatField(default=60.0, help_text='Confidence % (0–100) below which the AI decision always requires HITL approval.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about the current threshold configuration.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
