# Generated by Django 4.2.29 on 2026-03-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hubskumapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hubskumapping',
            name='lead_time_hours',
            field=models.IntegerField(blank=True, default=24, help_text='Production time in hours', null=True),
        ),
        migrations.AddField(
            model_name='hubskumapping',
            name='max_daily_production',
            field=models.IntegerField(blank=True, default=0, help_text='Units per day', null=True),
        ),
        migrations.AddField(
            model_name='hubskumapping',
            name='priority',
            field=models.IntegerField(blank=True, default=1, help_text='AI order assignment priority (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='hubskumapping',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_mappings', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='hubskumapping',
            unique_together={('hub', 'product')},
        ),
        migrations.RemoveField(
            model_name='hubskumapping',
            name='parts_required',
        ),
        migrations.RemoveField(
            model_name='hubskumapping',
            name='production_time',
        ),
        migrations.RemoveField(
            model_name='hubskumapping',
            name='sku',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
