# Generated by Django 4.2.29 on 2026-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_alter_hubskumapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='supported_skus',
            field=models.CharField(blank=True, help_text='Comma-separated SKUs supported by this hub', max_length=255, null=True),
        ),
    ]
